- name: Resolve git target username
  ansible.builtin.set_fact:
    username: "{{ username | default(wsl_default_user | default(default_user | default(ansible_user_id)), true) }}"

- name: Prompt for git username
  pause:
    prompt: "Enter git username"
  register: git_user_name_prompt

- name: Prompt for git email
  pause:
    prompt: "Enter git email"
  register: git_user_email_prompt

- name: Set git username
  command: git config --global user.name "{{ git_user_name_prompt.user_input }}"
  become_user: "{{ username }}"
  when: git_user_name_prompt.user_input | length > 0

- name: Set git email
  command: git config --global user.email "{{ git_user_email_prompt.user_input }}"
  become_user: "{{ username }}"
  when: git_user_email_prompt.user_input | length > 0