# Defaults for the wsl_setup role
wsl_default_user: root

# Packages per package manager
pkg_map:
  apt:
    - apt-transport-https
    - build-essential
    - git
    - wget
    - curl
    - gnupg
    - htop
    - zip
    - unzip
    - ca-certificates
    - lsb-release
    - ripgrep
    - fd-find
  pacman:
    - base
    - sudo
    - openssh
    - git
    - curl
    - wget
    - gnupg
    - htop
    - zip
    - unzip
    - make
    - ripgrep
    - fd